name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD  }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            devopswithsam/argodemo:latest
            devopswithsam/argodemo:${{ github.run_number }}
      - name: Fetch argocd-k8s-deploy repository
        uses: actions/checkout@v2
        with:
          repository: iam-sameera/argocd-k8s-deploy
          path: argocd-k8s-deploy
      - name: Update deployment YAML
        run: |
          sed -i "s|image: devopswithsam/argodemo:[0-9]*|image: devopswithsam/argodemo:${{ github.run_number }}|g" argocd-k8s-deploy/deployment.yml
      - name: Commit and push changes
        run: |
          cd argocd-k8s-deploy
          git config --global user.email "devopssameera@gmail.com"
          git config --global user.name "Sameera Dissanayaka"
          git add deploy.yml
          git commit -m "Update deployment image tag to ${{ github.run_number }}"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/iam-sameera/argocd-k8s-deploy.git
          git push origin main
